spring.application.name=authService

spring.datasource.url=jdbc:postgresql://localhost:5432/authService
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=pgadmin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.rememeberme.key=VERY-SECRET-KEY